[tool.poetry]
name = "texture-vae"
version = "0.1.0"
description = ""
authors = ["Tobias Lang <tobias@motesque.com>"]
readme = "README.md"
packages = [{include = "texture_vae"}]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
tqdm = "^4.64.1"
tensorboard = "^2.11.0"
torchsummary = "^1.5.1"
pytest = "^7.2.0"
click = "^8.1.3"
onnx = "^1.12.0"
onnxruntime = "^1.13.1"
pyyaml = "^6.0"
matplotlib = "^3.5"
setuptools = "59.5.0"


[tool.poetry.scripts]
vae-crop-gen = "texture_vae.cli.crop_gen:create_image_crops"
vae-onnx = "texture_vae.utils.export_onnx:main"

[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = "^22.10.0"
jupyterlab = "^3.5.0"
#ipywidgets

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
