model:
  latent_dims: 32
  texture_size: 128
  kl_weight: 7e-4
lr: 5e-4
epochs: 500
snapshots: "../snapshots_mssim"
train_images: "../bricks1000"
logs:
  logdir: "../tb/runs"
  experiment_name: "mmsim32_7e-4"

