model:
  latent_dims: 32
  texture_size: 128
  kl_weight: 3e-4
lr: 1e-3
epochs: 2000
snapshots: "../snapshots_mssim"
train_images: "../bricks1000"
logs:
  logdir: "../tb/runs"
  experiment_name: "mmsim32_3e-4"

