model:
  latent_dims: 32
  texture_size: 128
  kl_weight: 5e-4
lr: 5e-4
epochs: 500
snapshot: "../snapshots_mssim/lat32_res128_kl5e-4.pth"
train_images: "../bricks1000"
logs:
  logdir: "../tb/runs"
  experiment_name: "lat32_res128_kl5e-4"

